services:
  website:
    image: nginx
    depends_on:
      database:
        condition: service_healthy

  database:
    container_name: mysql8
    image: mysql:8.0
    command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: teste
      MYSQL_DATABASE: teste
      MYSQL_USER: teste
      MYSQL_PASSWORD: teste
    ports:
      - 3307:3306
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - './docker/db/data:/var/lib/mysql'